version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory:
      - "/src/Extensions/Integration"
        # This traces below the dependencies through the dependency chain:
        # Generator3, GirModel, GirLoader
      - "/src/Generation/GirTool"
    schedule:
      interval: "daily"
