version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directories:
      - "/src/Extensions/GObject-2.0.Integration"
        # This traces below the dependencies through the dependency chain:
        # Generator3, GirModel, GirLoader
      - "/src/Generation/GirTool"
    schedule:
      interval: "daily"
